### ISSUE TITLE
[BUG] Some not cleaned up trash

### ISSUE THREAD

**Issue by mtkusbdevice** [dest4590/MineCore#4]
**Describe the bug**
Modpack creators leaved the SEUS PTGI E12 shader pack settings in the "shaderpacks" folder.

**To Reproduce**
1. Go to Shader Packs settings
2. Click on 'Open folder'
3. Look
4. See leaved trash named "SEUS_PTGI_E12.zip.txt"

**Expected behavior**
I was expecting to see an completely empty folder 

**Screenshots**
![image](https://github.com/dest4590/MineCore/assets/122752743/c9ca8ac3-715c-460f-b0e9-9c604e3a0c9d)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by arsenii754** [comment]
uzhe pofixil

already fixed

**Comment by dest4590** [comment]
my bad
